In [5]:
import numpy as np

def main():
    arr = np.array([[1, 2], [3, 4]])  # Given array
    eig_val, eig_vec = np.linalg.eig(arr)
    determinant = int(np.linalg.det(arr))
    print("Eigenvalues:")
    print(eig_val)
    print("\nEigenvectors:")
    print(eig_vec)
    print("\nDeterminant:")
    print(determinant)
    
    vec1 = np.array([1,2,3])
    vec2 = np.array([4,5,6])
    output = np.cross(vec1, vec2)
    print("\nCross Product:")
    print(output)
    
    A = np.array([[1,2,-2],[2,1,-5],[1,-4,1]])
    b = np.array([-15,-21,18])
    x = np.linalg.solve(A,b)
    print("\nSolution:")
    print(x)
    
if __name__ == "__main__":
    main()

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Determinant:
-2

Cross Product:
[-3  6 -3]

Solution:
[-1. -4.  3.]
